federation_version: 2
subgraphs:
  taksk:
    routing_url: http:localhost:8080/
    schema:
      subgraph_url: http:localhost:8080/
  users:
    routing_url: http:localhost:8081/
    schema:
      subgraph_url: http:localhost:8081/