// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Task struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type TaskInput struct {
	ID     *string `json:"id"`
	Text   string  `json:"text"`
	UserID string  `json:"userId"`
}

type User struct {
	ID    string  `json:"id"`
	Tasks []*Task `json:"tasks"`
}

func (User) IsEntity() {}
